language: python
python:
- '3.9'
install:
- pip install -r requirements.txt
env:
  global:
    secure: HZN92N9cBqfeSxo8zG9NKe0mvvsvXCghqoWe8T9lzOMfQOBijUobHRq3EFHLHzZMxd/Ozg1nRaq5a1UmNHFXeM3NE/6tdukbRgke5KMwYNKBOQuHuAk/DtsLD2dX08b5D4LsRstY3gh+wwKdvzcxe2aZ2sR930btxdIJMOri5ovS4KgnhnlFZyBFRlXSO5HmJIZQYUCMsDMhaaas8Qkk5XEgpYvN/rdzqecp1QDRbMoUangSbXkAj+jjzVUw6Nm1/s6LoFjdTZM4mlZO1+23RahPuIcf1umhzvAk5R0KZvez6KWheHYjBV60jm5ONDrl/qx4Q5CBq4nkV3bkywQkVWgTCXKL1SEV1CsP3tXParl4VTE8qdAlr+iEFp05pytOBvl6Nn9YmltTfZPvNb1vWO10ZzRB8ndOFzCleaXfmjQSklU9p8QhClHzYzppvbAL+2xS2cwZRI1K3UlpJ9lv0zEB7tVSlEdPytOdF4bC4tQPR2Iv9SAJQLK9Xp2hzmKkORJdWU2KgI4ioWu3tAeofAlTvKGjXoT8Yea/KYwoZOngnEDq8T8Up+XWQ+03JxPPtavvrlArKfNSrqtLTMqeeeeURFBUEu096RJJP3GUutM5h2KgyHuSkT7CP8S24L/K2va9duk1G3r4MrPhvdJ6uanPDcvHLkVHKqaePt6QIq8=


script:
- black --check .
- flake8 --max-line-length=150 .
- coverage run manage.py test

after_script:
- coveralls
- echo "Build finished"
  

