language: python
python:
- '3.9'
install:
- pip install -r requirements.txt
env:
  global:
    secure: HZN92N9cBqfeSxo8zG9NKe0mvvsvXCghqoWe8T9lzOMfQOBijUobHRq3EFHLHzZMxd/Ozg1nRaq5a1UmNHFXeM3NE/6tdukbRgke5KMwYNKBOQuHuAk/DtsLD2dX08b5D4LsRstY3gh+wwKdvzcxe2aZ2sR930btxdIJMOri5ovS4KgnhnlFZyBFRlXSO5HmJIZQYUCMsDMhaaas8Qkk5XEgpYvN/rdzqecp1QDRbMoUangSbXkAj+jjzVUw6Nm1/s6LoFjdTZM4mlZO1+23RahPuIcf1umhzvAk5R0KZvez6KWheHYjBV60jm5ONDrl/qx4Q5CBq4nkV3bkywQkVWgTCXKL1SEV1CsP3tXParl4VTE8qdAlr+iEFp05pytOBvl6Nn9YmltTfZPvNb1vWO10ZzRB8ndOFzCleaXfmjQSklU9p8QhClHzYzppvbAL+2xS2cwZRI1K3UlpJ9lv0zEB7tVSlEdPytOdF4bC4tQPR2Iv9SAJQLK9Xp2hzmKkORJdWU2KgI4ioWu3tAeofAlTvKGjXoT8Yea/KYwoZOngnEDq8T8Up+XWQ+03JxPPtavvrlArKfNSrqtLTMqeeeeURFBUEu096RJJP3GUutM5h2KgyHuSkT7CP8S24L/K2va9duk1G3r4MrPhvdJ6uanPDcvHLkVHKqaePt6QIq8=


script:
- black --check .
- flake8 --max-line-length=150 .
- coverage run manage.py test

after_script:
- coveralls
- echo "Build finished"

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: C5Wreb6sk9KkZ6LziOASAk31WNUcvkfUieZ174rBTaHi9DYmFGz2YSAewPrSetMmO6hUu9kUPy8/6z+ib00M/OvUMd+4mDai41gBxDAlQR4tZlbir9okfw0WEvPMEDp6EvFsZ5ptINc6ADWXQ0U99gSknhLWjJPs6OAaU4n7fpuzwvsy7kVB74Py8miy5vMWTjVClL8LyNtMoZzsskmUgorZrjiaWrLqxX8Ruh0ETYhhfF0izLG7gvMTzBdaMjdDEMtdnM8qYBpiOSq+WipkoKf8DesUSMDR/YMM7kuqOoWUYSi7yv7ff4IKFnRHx+rBFMVZ3q0dkdC5zpdNGpkE5VNBLz6kvcmMIXuFm8enOC6WVbiToJhCTmnHJoQx0+lOezB5j2TsB/n9np6XOKIAbm/8ELq+7OTfEK4PAtxJYFpkFrHPZYh5FxZTvfsXKx2VeyWxbq5co1JhUS84frceBIv0pet0qHRcKLCOVDlJT1Z37yvmIry6Q1WzUKOeTIm1CJFWKRwYUSLgO/ozBjZuky2ktOyLf37UBJGjcz/dLEMvYx9Y15dOm8DpTL5J5tlgdU5RalSSRjMLAcZ0m/10mq1vy+LeOthCQHHkamEOvdwt6ytzkwDRzVUrap1ecw6HBxDUWu8u6VGvmYPYZdhHsRxhOFvlpQjvp6bqRl1gbCA=
  secret_access_key:
    secure: EQkCSh7eNBDLmXyH+5ssAuBkODf9W3/07Z2NGkUXX5P2JvIVK3WmqV2Qxv0EKTyciEr73WQQpKKp75f0LRh1Ycd6CLRRm+8DPDCYSAVJ9ZG2Oh2u01zo8em3vjr/FZieS+Zxurq2p3Hg42qHGkWptWL24vCrLvDZEoQCpsALyMRzC1zESv08U8PqLgPKuFV9532XVMnGTuqGKmhTPdGJmnOQynZVVK1nQq/dRPN1yJhBhk0cMCulBRGgoOVuxGonEgvaxsFsEwFjJ0chx6eDC/sBpdTltgA/o5VEnqyY3dNTg1+6FJifDFxqFDOVeK2iqQYZehRh4d2Du0OB+XzjXHNIkVK/ULFFXpaYMBK2Y3VJDhXajEEc9/Hhyl9npOA2JztmMapbN0kvP/sVGYNzEEYKsDiFhNK79dzWvo1Wih9ZNQslEj+kIkXrupckmEBHrUx09teflU43WIihhwIht7sSSAVJntkfrwuNRiluopeOGz03WaNmbQiYHCjHExmUnA3CrJ9wpBi2IYclpqiGHPX3PNrKolAzrBrS/fZNqj9mZAo/lAETnQx9buO4HP53XuOHMCltPndqo0eOAM4OJciNfsqhKQpfwBmKq77Pcdjer9syPqQWLcissiXj9hsfQgEXg/rMKgY4X9OwypleJVu0iEUSwXRbUOlpDE95osU=
  region: us-east-2
  app: polls-app
  env: polls-app
  bucket_name: elasticbeanstalk-us-east-2-682033502272
  on:
    repo: nsh2207/software-homework-1-django-polls
    branch: main
  skip_cleanup: 'true'
  

